### ISSUE TITLE
Relative basedir on windows fails to resolve anything

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [substack/node-resolve#78]
The following will fail (windows 8.1):

``` javascript
var path = require('resolve').sync(
        'resolve/test/core.js',
        {
                basedir: 'lib\\foo'
        }
);
// Error: Cannot find module 'resolve/test/core.js' from 'lib\foo'
```

However, it works properly if I do the following instead:

``` javascript
var path = require('resolve').sync(
        'resolve/test/core.js',
        {
                basedir: require('path').resolve('lib\\foo')
        }
);
// D:\Users\joris_000\Projects\foo\node_modules\resolve\test\core.js
```

It looks like something is going wrong here: [node-modules-paths.js:8](https://github.com/substack/node-resolve/blob/9d6b7af28c054676d6ea8a5037353ed750ea13bb/lib/node-modules-paths.js#L8)

If I log the paths that are being created at [line 26](https://github.com/substack/node-resolve/blob/9d6b7af28c054676d6ea8a5037353ed750ea13bb/lib/node-modules-paths.js#L26), I get the following output:

```
/D:\Users\joris_000\Documents\Projects\foo\lib\foo\node_modules
/D:\Users\joris_000\Documents\Projects\foo\lib\node_modules
/D:\Users\joris_000\Documents\Projects\foo\node_modules
/D:\Users\joris_000\Documents\Projects\node_modules
/D:\Users\joris_000\Documents\node_modules
/D:\Users\joris_000\node_modules
/D:\Users\node_modules
/D:node_modules
```

If I move line 18 before line 8, so that the end result is this:

``` javascript
module.exports = function (start, opts) {
    var modules = opts.moduleDirectory
        ? [].concat(opts.moduleDirectory)
        : ['node_modules']
    ;

    start = path.resolve(start);

    var prefix = '/';
    if (/^([A-Za-z]:)/.test(start)) {
        prefix = '';
    } else if (/^\\\\/.test(start)) {
        prefix = '\\\\';
    }
    var splitRe = process.platform === 'win32' ? /[\/\\]/ : /\/+/;

    // ensure that `start` is an absolute path at this point,
    // resolving againt the process' current working directory
    var parts = start.split(splitRe);
...
```

It seems to be fixed, but I am not sure how this change affects other platforms

**Comment by Joris-van-der-Wel** [comment]
I was able to reproduce it again with `resolve@0.7.0`. I think it is fixed in `resolve@1.2.0`:

```
D:\Users\J\Desktop\foo>node --version
v6.1.0

D:\Users\J\Desktop\foo>npm --version
3.8.6

D:\Users\J\Desktop\foo>echo var path = require('resolve').sync('resolve/test/core.js', {basedir: 'lib\\bar'}); console.log('The resolved path is:', path); > resolve-issue.js

D:\Users\J\Desktop\foo>echo console.log('The resolved path is:', path); >> resolve-issue.js

D:\Users\J\Desktop\foo>mkdir lib

D:\Users\J\Desktop\foo>mkdir lib\bar

D:\Users\J\Desktop\foo>npm i resolve@0.7.0
D:\Users\J\Desktop\foo
`-- resolve@0.7.0

D:\Users\J\Desktop\foo>node resolve-issue.js
D:\Users\J\Desktop\foo\node_modules\resolve\lib\sync.js:32
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module 'resolve/test/core.js' from 'lib\bar'

D:\Users\J\Desktop\foo>npm i resolve@latest
D:\Users\J\Desktop\foo
`-- resolve@1.2.0

D:\Users\J\Desktop\foo>node resolve-issue.js
The resolved path is: D:\Users\J\Desktop\foo\node_modules\resolve\test\core.js
```

**Comment by Joris-van-der-Wel** [comment]
Here is the commit that fixed it (35b2b642d91e9b81e7cc26b6fd19912e18901d55):
```
35b2b642d91e9b81e7cc26b6fd19912e18901d55 is the first bad commit
commit 35b2b642d91e9b81e7cc26b6fd19912e18901d55
Author: Gosha Arinich <me@goshakkk.name>
Date:   Sat Jan 23 18:19:27 2016 +0300

    Fix node_modules paths on Windows

    This change moves 'prefix' test to happen after the absolute path is
    resolved. Without it, the prefix tests never actually fire when starting
    with a relative path, and the resulting dirs all end up looking like
    [ '/C:..', '/C:...' ] instead of [ 'C:...', 'C:...' ]

:040000 040000 a3f2f25432ff09fd3588d3554015961cf80e8204 f9320061422bb78c9f782eb55c8b39e606ad1b94 M      lib
```

**Comment by ljharb** [comment]
Thanks for confirming!

Fixed by #91.
